### ISSUE TITLE
Check why some components aren't align correctly when using with React

### ISSUE THREAD

**Issue by MangelMaxime** [MangelMaxime/Fulma#125]
Explore why #88 occure

I have the same problem with checkradio.

My SCSS code to fix it:

```scss
.is-checkradio[type="checkbox"] + label::before,
.is-checkradio[type="checkbox"] + label::after {
    margin-top: 0.25em
}
```

If this problem can't be fixed by ourself, we will need to provide and style file to fix the problem.

**Comment by et1975** [comment]
cc @2sComplement

**Comment by 2sComplement** [comment]
Could this be flexbox-related? Alignment issue for me when using flexboxes are usually solved by setting `align-items` or `justify-content` depending on the flex direction.

**Comment by MangelMaxime** [comment]
Not sure, but if I look at [Switch](https://wikiki.github.io/form/switch/) even in HTML there seems to have alignment problems.

So perhaps, it's the CSS component having a problem and not Fulma/React.

**Comment by MangelMaxime** [comment]
Me neither, but I added this lines:

https://github.com/MangelMaxime/Fulma/blob/master/docs/scss/main.scss#L136-L141

```scss
// Fix Bulma radio & checkbox margin
// Seems to be a problem with React
input[type="checkbox"],
input[type="radio"] {
    margin-right: 0.5em;
}
```

to the doc site one day and I know it was needed. When I wrote them, I tested to copy/paste the html views directly from the browser to an .html file and it was working nicely.

After, it's indeed to possible that my .html file was much simpler in term of layout. And so perhaps the bugs is due to a side effect of nested components.

I will check the CSS libraries first and send PR to fix the display if needed and then check again my different applications without the custom scss fix.
